language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run web sh -c "python3 manage.py test"

deploy:
  run: python3 manage.py migrate
  provider: heroku
  api_key: 
    secure: b567d4d9-45f8-41d4-af06-9dd825babd2b
  app: guarded-basin-80319
  on:
    repo: thywoe/shopperz-api