version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dearmama0
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./shopperz:/shopperz-api
    ports:
        - "8000:8000"
    depends_on:
        - migration
  migration:
    build: .
    command: python manage.py migrate 
    depends_on:
        - db